- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Get DNS Server Group Object
      cisco.fmcansible.fmc_configuration:
        operation: "getAllDNSServerGroupObject"
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
        filters:
          name: "{{ delete_dnservergroupobject_name }}"
        register_as: dnsobject

    - name: Delete FQDN network for Cisco DevNet
      cisco.fmcansible.fmc_configuration:
        operation: deleteDNSServerGroupObject
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
          objectId: '{{ dnsobject[0].id }}'
