- hosts: all
  connection: httpapi
  vars_files:
    - vars.yml
  tasks:
    - name: Get Domain UUID
      cisco.fmcansible.fmc_configuration:
        operation: getAllDomain
        register_as: domain

    - name: Get Security Zone Object
      cisco.fmcansible.fmc_configuration:
        operation: "getAllSecurityZoneObject"
        path_params:
            domainUUID: "{{ domain[0].uuid }}"
        filters:
          name: "{{ delete_securityzone_name }}"
        register_as: seczone

    - name: Delete security zone
      cisco.fmcansible.fmc_configuration:
        operation: deleteSecurityZoneObject
        path_params:
          domainUUID: '{{ domain[0].uuid }}'
          objectId: '{{ seczone[0].id }}'
